{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosaicdb.fullname" . }}-auth
  labels: {{ include "mosaicdb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.jwtSecret }}
  jwt-secret: {{ .Values.auth.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.apiKeyEncryptionKey }}
  api-key-encryption-key: {{ .Values.auth.apiKeyEncryptionKey | b64enc | quote }}
  {{- else }}
  api-key-encryption-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
