{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mosaicdb.serviceAccountName" . }}
  labels: {{ include "mosaicdb.labels" . | nindent 4 }}
{{- end }}
